"""Canonical Excel audit workbook schema.

Every broker adapter must produce these sheets in this order. The columns below
are the stable workbook contract for tax and reconciliation layers.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class SheetDefinition:
    name: str
    required_columns: tuple[str, ...]
    description: str


CANONICAL_WORKBOOK_SHEETS: tuple[SheetDefinition, ...] = (
    SheetDefinition(
        "Instruments",
        (
            "symbol",
            "description",
            "conid",
            "security_id",
            "underlying",
            "listing_exchange",
            "multiplier",
            "type",
            "code",
            "year",
            "expiry",
            "delivery_month",
            "strike",
            "issuer",
            "maturity",
            "cusip",
            "country",
            "isin",
            "figi",
            "issuer_country",
            "offshore_flag",
            "issuer_outside_kz_flag",
            "preferential_tax_flag",
            "source_broker",
            "source_account",
            "source_report",
            "as_of_date",
        ),
        "Instrument master records collected from all encountered reports.",
    ),
    SheetDefinition(
        "CorporateActions",
        (
            "date",
            "symbol",
            "isin",
            "action_type",
            "description",
            "quantity",
            "proceeds",
            "value",
            "currency",
            "realized_pl",
            "source_report",
        ),
        "Mergers, redemptions, buybacks, spin-offs and similar actions.",
    ),
    SheetDefinition(
        "Dividends",
        (
            "date",
            "pay_date",
            "symbol",
            "isin",
            "country",
            "currency",
            "gross_amount",
            "withholding_tax",
            "net_amount",
            "kzt_rate",
            "gross_amount_kzt",
            "tax",
            "tax_kzt",
            "offshore_flag",
            "kase_aix_preferential_flag",
            "source_report",
        ),
        "Dividend income and foreign tax withheld.",
    ),
    SheetDefinition(
        "Transfers",
        (
            "date",
            "transfer_type",
            "direction",
            "asset_type",
            "symbol",
            "isin",
            "currency",
            "quantity",
            "price",
            "enter_date",
            "amount",
            "broker_comment",
            "counterparty",
            "source_report",
        ),
        "Cash and security deposits, withdrawals and account transfers.",
    ),
    SheetDefinition(
        "Trades",
        (
            "date_time",
            "trade_id",
            "trade_type",
            "symbol",
            "isin",
            "asset_type",
            "quantity",
            "price",
            "multiplier",
            "amount",
            "commission",
            "amount_with_commission",
            "currency",
            "exchange",
            "country",
            "source_report",
        ),
        "Raw trades in execution order after broker normalization.",
    ),
    SheetDefinition(
        "Fifo",
        (
            "asset_type",
            "symbol",
            "isin",
            "currency",
            "country",
            "position_type",
            "enter_date",
            "enter_quantity",
            "enter_price",
            "enter_multiplier",
            "enter_amount",
            "enter_commission",
            "exit_date",
            "exit_quantity",
            "exit_price",
            "exit_multiplier",
            "exit_amount",
            "exit_commission",
            "acquisition_cost_with_commission",
            "pnl_before_commission",
            "pnl_after_all_commissions",
            "pnl",
            "kzt_rate",
            "exit_amount_kzt",
            "acquisition_cost_with_commission_kzt",
            "pnl_kzt",
            "source_trade_id",
        ),
        "Realized results calculated by FIFO with commission allocation.",
    ),
    SheetDefinition(
        "Positions",
        (
            "year",
            "date",
            "asset_type",
            "symbol",
            "isin",
            "currency",
            "country",
            "quantity",
            "price",
            "multiplier",
            "amount",
            "kzt_rate",
            "amount_kzt",
        ),
        "End-of-year portfolio positions by instrument.",
    ),
    SheetDefinition(
        "Interest",
        (
            "date",
            "description",
            "currency",
            "gross_amount",
            "withholding_tax",
            "net_amount",
            "kzt_rate",
            "gross_amount_kzt",
            "withholding_tax_kzt",
            "net_amount_kzt",
            "source_report",
        ),
        "Interest on broker cash balances.",
    ),
    SheetDefinition(
        "Coupons",
        (
            "date",
            "symbol",
            "isin",
            "country",
            "currency",
            "gross_amount",
            "withholding_tax",
            "net_amount",
            "kzt_rate",
            "gross_amount_kzt",
            "withholding_tax_kzt",
            "net_amount_kzt",
            "offshore_flag",
            "source_report",
        ),
        "Bond coupon income.",
    ),
    SheetDefinition(
        "CashBalances",
        (
            "year",
            "date",
            "currency",
            "ending_cash",
            "ending_cash_kzt",
            "source_report",
        ),
        "Cash balances used to reconcile ending cash.",
    ),
    SheetDefinition(
        "Years_Results",
        (
            "table",
            "year",
            "flag",
            "country",
            "currency",
            "pnl",
            "pnl_kzt",
            "amount",
            "amount_kzt",
            "only_profit",
            "only_profit_kzt",
            "withhold_kzt",
            "tax_kzt",
            "tax_kzt_withhold",
        ),
        "Yearly result blocks by income category, flag and currency.",
    ),
    SheetDefinition(
        "Unprocessed",
        (
            "severity",
            "reason",
            "details",
            "source_sheet",
            "source_report",
            "trade_id",
            "date_time",
            "symbol",
            "isin",
            "asset_type",
            "currency",
            "quantity",
            "price",
            "amount",
            "commission",
        ),
        "Rows that were preserved but could not be fully processed.",
    ),
    SheetDefinition(
        "Reconciliation",
        (
            "metric",
            "severity",
            "year",
            "currency",
            "instrument_key",
            "broker_value",
            "canonical_value",
            "difference",
            "tolerance",
            "source",
            "details",
        ),
        "Differences between raw broker report totals and canonical workbook data.",
    ),
)

CANONICAL_SHEET_NAMES: tuple[str, ...] = tuple(sheet.name for sheet in CANONICAL_WORKBOOK_SHEETS)
CANONICAL_REQUIRED_COLUMNS: dict[str, tuple[str, ...]] = {
    sheet.name: sheet.required_columns for sheet in CANONICAL_WORKBOOK_SHEETS
}

YEARS_RESULTS_TABLE_COLUMNS: dict[str, tuple[str, ...]] = {
    "Yearly Trades": ("year", "flag", "currency", "pnl", "pnl_kzt", "tax_kzt"),
    "Yearly Corp Actions": ("year", "flag", "currency", "pnl", "pnl_kzt", "tax_kzt"),
    "Yearly FX Trades": ("year", "flag", "currency", "pnl", "pnl_kzt", "tax_kzt"),
    "Yearly Dividends": (
        "year",
        "flag",
        "country",
        "currency",
        "amount",
        "amount_kzt",
        "withhold_kzt",
        "tax_kzt",
        "tax_kzt_withhold",
    ),
    "Yearly Interest": (
        "year",
        "flag",
        "currency",
        "amount",
        "amount_kzt",
        "only_profit",
        "only_profit_kzt",
        "tax_kzt",
    ),
    "Yearly Coupons": (
        "year",
        "flag",
        "currency",
        "amount",
        "amount_kzt",
        "withhold_kzt",
        "tax_kzt",
        "tax_kzt_withhold",
    ),
}


def required_columns(sheet_name: str) -> tuple[str, ...]:
    try:
        return CANONICAL_REQUIRED_COLUMNS[sheet_name]
    except KeyError as exc:
        raise KeyError(f"Unknown canonical sheet: {sheet_name}") from exc
