[paths]
processed_data = ""
output_data = ""
form270_template = ""

[form270]

# excel
[[form270.jobs]]
id = ""
broker = ""
account_id = ""

# merge_excel
[[form270.jobs]]
id = ""
workbooks = []
fio1 = ""
fio2 = ""
fio3 = ""

# joint_excel
[[form270.jobs]]
id = ""
file_name = ""

# 270_json
[[form270.jobs]]
id = ""
file_name = ""
civ_servant = false
tax_year = 0
fio1 = ""
fio2 = ""
fio3 = ""
iin = ""
phone = ""
email = ""
ogd_residence = ""
ogd_location = ""

[form270.banks.ib]
code = ""
name = ""
country = ""
